export const topics = [
    {
        name: 'Data Structures',
        questions: [
            {
                category: 'Data Structures',
                question: 'What is the time complexity of inserting an element at the end of an array?',
                options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'],
                correctAnswer: 'O(1)',
            },
            {
                category: 'Data Structures',
                question: 'Which data structure uses LIFO (Last In, First Out)?',
                options: ['Queue', 'Stack', 'Array', 'Linked List'],
                correctAnswer: 'Stack',
            },
            {
                category: 'Data Structures',
                question: 'What is the space complexity of a singly linked list with n nodes?',
                options: ['O(1)', 'O(n)', 'O(n^2)', 'O(log n)'],
                correctAnswer: 'O(n)',
            },
            {
                category: 'Data Structures',
                question: 'Which sorting algorithm has the best average-case time complexity?',
                options: ['Bubble Sort', 'Selection Sort', 'Quick Sort', 'Insertion Sort'],
                correctAnswer: 'Quick Sort',
            },
            {
                category: 'Data Structures',
                question: 'What is a binary tree with only one node called?',
                options: ['Leaf', 'Root', 'Branch', 'Edge'],
                correctAnswer: 'Root',
            },
            {
                category: 'Data Structures',
                question: 'What is the worst-case time complexity of merge sort?',
                options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
                correctAnswer: 'O(n log n)',
            },
            {
                category: 'Data Structures',
                question: 'Which data structure is best for implementing a priority queue?',
                options: ['Array', 'Linked List', 'Heap', 'Stack'],
                correctAnswer: 'Heap',
            },
            {
                category: 'Data Structures',
                question: 'What is the time complexity of searching in a balanced binary search tree?',
                options: ['O(n)', 'O(log n)', 'O(n^2)', 'O(1)'],
                correctAnswer: 'O(log n)',
            },
            {
                category: 'Data Structures',
                question: 'Which algorithm is used to detect a cycle in a linked list?',
                options: ['Dijkstra’s', 'Floyd’s Cycle Detection', 'Kruskal’s', 'Prim’s'],
                correctAnswer: 'Floyd’s Cycle Detection',
            },
            {
                category: 'Data Structures',
                question: 'What is the primary advantage of a hash table?',
                options: ['Sorted data', 'Constant time lookup', 'Dynamic resizing', 'Tree structure'],
                correctAnswer: 'Constant time lookup',
            },
        ],
    },
    {
        name: 'Networking',
        questions: [
            {
                category: 'Networking',
                question: 'What does HTTP stand for?',
                options: ['HyperText Transfer Protocol', 'High Throughput Protocol', 'Hyper Terminal Protocol', 'Host Transfer Protocol'],
                correctAnswer: 'HyperText Transfer Protocol',
            },
            {
                category: 'Networking',
                question: 'Which layer of the OSI model handles data encryption?',
                options: ['Application', 'Transport', 'Presentation', 'Network'],
                correctAnswer: 'Presentation',
            },
            {
                category: 'Networking',
                question: 'What is the default port for HTTPS?',
                options: ['80', '443', '21', '8080'],
                correctAnswer: '443',
            },
            {
                category: 'Networking',
                question: 'What does DNS stand for?',
                options: ['Dynamic Network System', 'Domain Name System', 'Data Network Service', 'Distributed Name Server'],
                correctAnswer: 'Domain Name System',
            },
            {
                category: 'Networking',
                question: 'Which protocol ensures reliable data transfer?',
                options: ['UDP', 'TCP', 'FTP', 'SMTP'],
                correctAnswer: 'TCP',
            },
            {
                category: 'Networking',
                question: 'What is an IP address?',
                options: ['A physical address', 'A unique network identifier', 'A software protocol', 'A data packet'],
                correctAnswer: 'A unique network identifier',
            },
            {
                category: 'Networking',
                question: 'Which device operates at the Data Link layer?',
                options: ['Router', 'Switch', 'Gateway', 'Firewall'],
                correctAnswer: 'Switch',
            },
            {
                category: 'Networking',
                question: 'What is the purpose of a subnet mask?',
                options: ['Encrypt data', 'Divide networks', 'Route packets', 'Assign ports'],
                correctAnswer: 'Divide networks',
            },
            {
                category: 'Networking',
                question: 'Which protocol is used for email transfer?',
                options: ['HTTP', 'FTP', 'SMTP', 'DNS'],
                correctAnswer: 'SMTP',
            },
            {
                category: 'Networking',
                question: 'What does NAT stand for?',
                options: ['Network Address Translation', 'Node Access Technology', 'Network Authentication Token', 'New Address Type'],
                correctAnswer: 'Network Address Translation',
            },
        ],
    },
    {
        name: 'React',
        questions: [
            {
                category: 'React',
                question: 'What is JSX in React?',
                options: ['A styling framework', 'A JavaScript syntax extension', 'A database library', 'A routing library'],
                correctAnswer: 'A JavaScript syntax extension',
            },
            {
                category: 'React',
                question: 'Which hook is used to handle side effects in React?',
                options: ['useState', 'useEffect', 'useContext', 'useReducer'],
                correctAnswer: 'useEffect',
            },
            {
                category: 'React',
                question: 'What is a React component?',
                options: ['A database model', 'A reusable UI piece', 'A server endpoint', 'A CSS class'],
                correctAnswer: 'A reusable UI piece',
            },
            {
                category: 'React',
                question: 'How do you pass data to a child component?',
                options: ['State', 'Props', 'Context', 'Hooks'],
                correctAnswer: 'Props',
            },
            {
                category: 'React',
                question: 'What is the virtual DOM?',
                options: ['A physical DOM copy', 'A lightweight DOM representation', 'A database schema', 'A CSS framework'],
                correctAnswer: 'A lightweight DOM representation',
            },
            {
                category: 'React',
                question: 'Which method is used to update state in a functional component?',
                options: ['setState', 'useState', 'updateState', 'changeState'],
                correctAnswer: 'useState',
            },
            {
                category: 'React',
                question: 'What does useContext do?',
                options: ['Manages state', 'Handles routing', 'Shares data without props', 'Performs HTTP requests'],
                correctAnswer: 'Shares data without props',
            },
            {
                category: 'React',
                question: 'What is the purpose of React Router?',
                options: ['State management', 'Navigation and routing', 'Data fetching', 'Styling components'],
                correctAnswer: 'Navigation and routing',
            },
            {
                category: 'React',
                question: 'What is a controlled component?',
                options: ['A component with no state', 'A component tied to form data', 'A component with props', 'A stateless function'],
                correctAnswer: 'A component tied to form data',
            },
            {
                category: 'React',
                question: 'Which lifecycle method is replaced by useEffect in functional components?',
                options: ['render', 'componentDidMount', 'setState', 'constructor'],
                correctAnswer: 'componentDidMount',
            },
        ],
    },
    {
        name: 'Angular',
        questions: [
            {
                category: 'Angular',
                question: 'What is the primary building block of an Angular application?',
                options: ['Module', 'Component', 'Service', 'Directive'],
                correctAnswer: 'Component',
            },
            {
                category: 'Angular',
                question: 'What is used for two-way data binding in Angular?',
                options: ['[(ngModel)]', '[ngFor]', '*ngIf', '@Input'],
                correctAnswer: '[(ngModel)]',
            },
            {
                category: 'Angular',
                question: 'What is an Angular module?',
                options: ['A UI component', 'A service provider', 'A container for related code', 'A routing library'],
                correctAnswer: 'A container for related code',
            },
            {
                category: 'Angular',
                question: 'Which directive repeats a portion of the DOM?',
                options: ['*ngIf', '*ngFor', 'ngSwitch', 'ngModel'],
                correctAnswer: '*ngFor',
            },
            {
                category: 'Angular',
                question: 'What is dependency injection in Angular?',
                options: ['A styling technique', 'A way to provide dependencies', 'A routing mechanism', 'A data binding method'],
                correctAnswer: 'A way to provide dependencies',
            },
            {
                category: 'Angular',
                question: 'What is the purpose of a service in Angular?',
                options: ['Render UI', 'Handle business logic', 'Style components', 'Manage routes'],
                correctAnswer: 'Handle business logic',
            },
            {
                category: 'Angular',
                question: 'Which command creates a new Angular component?',
                options: ['ng generate component', 'ng new component', 'ng create component', 'ng add component'],
                correctAnswer: 'ng generate component',
            },
            {
                category: 'Angular',
                question: 'What is the purpose of *ngIf?',
                options: ['Loop through data', 'Conditionally show elements', 'Bind data', 'Create components'],
                correctAnswer: 'Conditionally show elements',
            },
            {
                category: 'Angular',
                question: 'What is a pipe in Angular?',
                options: ['A routing tool', 'A data transformation tool', 'A state manager', 'A component generator'],
                correctAnswer: 'A data transformation tool',
            },
            {
                category: 'Angular',
                question: 'What is the Angular CLI?',
                options: ['A styling library', 'A command-line interface', 'A testing framework', 'A database tool'],
                correctAnswer: 'A command-line interface',
            },
        ],
    },
    {
        name: 'Computer Science',
        questions: [
            {
                category: 'Computer Science',
                question: 'What is an operating system?',
                options: ['A database', 'A hardware component', 'A software managing resources', 'A programming language'],
                correctAnswer: 'A software managing resources',
            },
            {
                category: 'Computer Science',
                question: 'What is the purpose of a CPU?',
                options: ['Store data', 'Execute instructions', 'Manage memory', 'Handle networking'],
                correctAnswer: 'Execute instructions',
            },
            {
                category: 'Computer Science',
                question: 'What does SQL stand for?',
                options: ['Simple Query Language', 'Structured Query Language', 'System Query Language', 'Standard Query Logic'],
                correctAnswer: 'Structured Query Language',
            },
            {
                category: 'Computer Science',
                question: 'What is object-oriented programming?',
                options: ['A styling method', 'A programming paradigm using objects', 'A database model', 'A networking protocol'],
                correctAnswer: 'A programming paradigm using objects',
            },
            {
                category: 'Computer Science',
                question: 'What is a primary key in a database?',
                options: ['A duplicate key', 'A unique identifier for a record', 'A foreign key', 'A data type'],
                correctAnswer: 'A unique identifier for a record',
            },
            {
                category: 'Computer Science',
                question: 'What is the purpose of normalization in databases?',
                options: ['Increase redundancy', 'Reduce redundancy', 'Encrypt data', 'Backup data'],
                correctAnswer: 'Reduce redundancy',
            },
            {
                category: 'Computer Science',
                question: 'What is a thread in computing?',
                options: ['A hardware component', 'A sequence of instructions', 'A database table', 'A network protocol'],
                correctAnswer: 'A sequence of instructions',
            },
            {
                category: 'Computer Science',
                question: 'What is the binary system?',
                options: ['A base-10 system', 'A base-2 system', 'A base-8 system', 'A base-16 system'],
                correctAnswer: 'A base-2 system',
            },
            {
                category: 'Computer Science',
                question: 'What is a deadlock in operating systems?',
                options: ['A fast process', 'A process waiting indefinitely', 'A memory leak', 'A network failure'],
                correctAnswer: 'A process waiting indefinitely',
            },
            {
                category: 'Computer Science',
                question: 'What is encapsulation in OOP?',
                options: ['Breaking code into modules', 'Hiding data within a class', 'Creating multiple instances', 'Inheriting classes'],
                correctAnswer: 'Hiding data within a class',
            },
        ],
    },
];